// -*- mode: c++ -*-
// 
// File MDF_2022_TX_TEST_FINAL2.C generated by TMultiDimFit::MakeRealCode
// on Mon Mar  4 15:54:36 2024
// ROOT version 6.26/02
//
// This file contains the function 
//
//    double  MDF(double *x); 
//
// For evaluating the parameterization obtained
// from TMultiDimFit and the point x
// 
// See TMultiDimFit class documentation for more information 
// 
//
// Static data variables
//
static int    gNVariables_TX    = 9;
static int    gNCoefficients_TX = 30;
static double gDMean_TX         = -0.000927136;
// Assignment to mean vector.
static double gXMean_TX[] = {
  -0.032222, -0.00855626, -0.00218828, -0.00764959, -0.186309, 0.0114463, 0.000204837, -0.323067, 0.0273372 };

// Assignment to minimum vector.
static double gXMin_TX[] = {
  -7.95958, -8.30958, -453.522, -0.0203062, 0.472963, -31.5632, 495.2, 0.0436094, -0.0252051 };

// Assignment to maximum vector.
static double gXMax_TX[] = {
  9.20384, 7.89871, -207.528, 0.0196931, 122.886, 23.7248, 735.197, 0.230435, 0.022531 };

// Assignment to coefficients vector.
static double gCoefficient_TX[] = {
  -0.00762302,
  -0.0164737,
  0.000443388,
  -0.00235124,
  0.000604624,
  0.0184955,
  -0.000737776,
  0.000689008,
  0.000221369,
  -0.000329877,
  -0.00260173,
  -0.000331444,
  -0.000620059,
  -0.0957786,
  -0.034931,
  0.128012,
  -0.000165339,
  0.0018771,
  -0.0229457,
  0.000123373,
  -0.0126958,
  -0.00525476,
  -0.000659275,
  -0.00124829,
  -0.000154265,
  -0.00329815,
  -0.000258246,
  -0.000807177,
  -0.000806871,
  0.00159211
 };

// Assignment to error coefficients vector.
static double gCoefficientRMS_TX[] = {
  3.54684e-12,
  2.07682e-11,
  2.42789e-11,
  4.39391e-11,
  1.97855e-11,
  5.75673e-11,
  1.99386e-11,
  1.6757e-11,
  2.00528e-11,
  3.0767e-11,
  2.99985e-11,
  6.88843e-11,
  7.47962e-11,
  3.40534e-11,
  1.27043e-11,
  4.52161e-11,
  7.46148e-12,
  3.42457e-11,
  1.48512e-11,
  1.90526e-12,
  4.0776e-11,
  1.55964e-11,
  9.04652e-12,
  6.45738e-12,
  1.62327e-11,
  1.45793e-11,
  5.40943e-12,
  2.22208e-11,
  1.80109e-11,
  3.55837e-11
 };

// Assignment to powers vector.
// The powers are stored row-wise, that is
//  p_ij = gPower[i * NVariables + j];
static int    gPower_TX[] = {
  1,  1,  1,  1,  1,  1,  1,  1,  1,
  2,  1,  1,  1,  1,  1,  1,  1,  1,
  2,  1,  2,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  1,  2,  1,  1,  2,  1,
  2,  1,  1,  1,  1,  1,  1,  2,  1,
  1,  1,  2,  1,  2,  1,  1,  1,  1,
  2,  1,  1,  1,  1,  1,  1,  3,  1,
  1,  1,  1,  1,  3,  1,  1,  2,  1,
  2,  1,  3,  1,  1,  1,  1,  1,  1,
  4,  1,  1,  1,  1,  1,  1,  1,  1,
  1,  1,  4,  1,  1,  1,  1,  2,  1,
  4,  1,  2,  1,  1,  1,  1,  1,  1,
  4,  1,  3,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  1,  1,  1,  1,  2,  1,
  1,  1,  1,  1,  1,  1,  2,  1,  1,
  1,  1,  1,  1,  2,  1,  1,  1,  1,
  3,  1,  1,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  1,  1,  1,  1,  3,  1,
  1,  1,  1,  1,  1,  1,  2,  2,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  2,
  1,  1,  2,  1,  1,  1,  1,  2,  1,
  1,  1,  2,  1,  1,  1,  2,  1,  1,
  1,  1,  2,  1,  1,  1,  1,  1,  3,
  1,  1,  4,  1,  1,  1,  1,  1,  1,
  1,  1,  2,  1,  1,  1,  1,  3,  1,
  1,  1,  2,  1,  1,  1,  2,  2,  1,
  1,  1,  2,  1,  1,  1,  3,  1,  1,
  1,  1,  2,  1,  3,  1,  1,  1,  1,
  1,  1,  2,  1,  1,  1,  1,  2,  3,
  1,  1,  4,  1,  2,  1,  1,  1,  1
};

// 
// The function   double MDF(double *x)
// 
double MDF_TX(double *x) {
  double returnValue = gDMean_TX;
  int    i = 0, j = 0, k = 0;
  for (i = 0; i < gNCoefficients_TX ; i++) {
    // Evaluate the ith term in the expansion
    double term = gCoefficient_TX[i];
    for (j = 0; j < gNVariables_TX; j++) {
      // Evaluate the polynomial in the jth variable.
      int power = gPower_TX[gNVariables_TX * i + j]; 
      double p1 = 1, p2 = 0, p3 = 0, r = 0;
      double v =  1 + 2. / (gXMax_TX[j] - gXMin_TX[j]) * (x[j] - gXMax_TX[j]);
      // what is the power to use!
      switch(power) {
      case 1: r = 1; break; 
      case 2: r = v; break; 
      default: 
        p2 = v; 
        for (k = 3; k <= power; k++) { 
          p3 = p2 * v;
          p1 = p2; p2 = p3; 
        }
        r = p3;
      }
      // multiply this term by the poly in the jth var
      term *= r; 
    }
    // Add this term to the final result
    returnValue += term;
  }
  return returnValue;
}

// EOF for MDF_2022_TX_TEST_FINAL2.C
