// -*- mode: c++ -*-
// 
// File MDF_2022_GTMC_TEST_FINAL3.C generated by TMultiDimFit::MakeRealCode
// on Tue Mar 12 08:57:37 2024
// ROOT version 6.26/02
//
// This file contains the function 
//
//    double  MDF(double *x); 
//
// For evaluating the parameterization obtained
// from TMultiDimFit and the point x
// 
// See TMultiDimFit class documentation for more information 
// 
//
// Static data variables
//
static int    gNVariables    = 10;
static int    gNCoefficients = 30;
static double gDMean         = 8.03813;
// Assignment to mean vector.
static double gXMean[] = {
  -0.0271904, -4.17464e-05, -0.00174448, -0.0460955, -0.00772815, -0.189341, 0.0523576, 0.00132584, -0.326492, 0.0495908 };

// Assignment to minimum vector.
static double gXMin[] = {
  -7.96977, -8.30535, -453.523, -0.0201213, -0.0203062, 0.129323, -34.2661, 495.2, 0.0436094, -0.0263204 };

// Assignment to maximum vector.
static double gXMax[] = {
  9.13907, 7.76551, -207.528, 0.0198783, 0.0196931, 123.47, 24.0078, 735.192, 0.230435, 0.022531 };

// Assignment to coefficients vector.
static double gCoefficient[] = {
  -2.27669,
  -3.685,
  -0.0186708,
  2.20742,
  0.788151,
  -1.05433,
  -2.36441,
  1.22692,
  -0.405218,
  0.0791297,
  2.15965,
  -1.86289,
  -0.0292301,
  0.0448109,
  0.597572,
  1.08836,
  0.022334,
  -0.0420318,
  0.0152709,
  0.0430481,
  0.718994,
  1.59364,
  0.00707664,
  -0.35026,
  0.128454,
  -1.0364,
  0.289438,
  0.113204,
  0.0416406,
  0.0302522
 };

// Assignment to error coefficients vector.
static double gCoefficientRMS[] = {
  3.1018e-12,
  9.73076e-12,
  1.32997e-11,
  3.00323e-11,
  9.17782e-12,
  1.4825e-11,
  2.72366e-11,
  3.02154e-11,
  1.48966e-11,
  5.69962e-12,
  5.15242e-11,
  7.29117e-11,
  5.09086e-12,
  5.92561e-12,
  3.31251e-11,
  7.53768e-11,
  4.96667e-12,
  1.13463e-11,
  1.90817e-11,
  9.5057e-12,
  9.99819e-11,
  1.07778e-10,
  1.30404e-11,
  4.09457e-11,
  1.99856e-11,
  1.46179e-10,
  6.39099e-11,
  3.05388e-11,
  1.87151e-11,
  1.07456e-11
 };

// Assignment to powers vector.
// The powers are stored row-wise, that is
//  p_ij = gPower[i * NVariables + j];
static int    gPower[] = {
  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  2,  1,
  2,  1,  1,  1,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  3,  1,
  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  2,  1,  1,  1,  1,  2,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  4,  1,
  1,  1,  1,  2,  1,  1,  1,  1,  3,  1,
  1,  1,  1,  3,  1,  1,  1,  1,  2,  1,
  1,  1,  1,  3,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  5,  1,
  1,  1,  1,  2,  1,  1,  1,  1,  4,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,
  1,  1,  1,  1,  1,  1,  1,  1,  1,  3,
  1,  1,  1,  3,  1,  1,  1,  1,  3,  1,
  1,  1,  1,  2,  1,  1,  1,  1,  6,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,
  1,  1,  1,  1,  1,  1,  1,  1,  2,  3,
  3,  1,  1,  2,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  4,  1,  1,  1,  1,  1,  1,
  2,  1,  1,  1,  1,  1,  1,  1,  5,  1,
  1,  1,  1,  2,  1,  2,  1,  1,  4,  1,
  1,  1,  2,  1,  1,  2,  1,  1,  4,  1,
  1,  1,  1,  2,  1,  2,  1,  2,  3,  1,
  1,  1,  1,  3,  1,  1,  1,  2,  3,  1,
  2,  1,  1,  1,  1,  3,  1,  1,  3,  1,
  2,  1,  1,  1,  1,  3,  1,  2,  2,  1,
  3,  1,  1,  3,  1,  1,  1,  1,  2,  1,
  1,  1,  1,  1,  1,  2,  1,  1,  2,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  1,  4
};

// 
// The function   double MDF(double *x)
// 
double MDF(double *x) {
  double returnValue = gDMean;
  int    i = 0, j = 0, k = 0;
  for (i = 0; i < gNCoefficients ; i++) {
    // Evaluate the ith term in the expansion
    double term = gCoefficient[i];
    for (j = 0; j < gNVariables; j++) {
      // Evaluate the polynomial in the jth variable.
      int power = gPower[gNVariables * i + j]; 
      double p1 = 1, p2 = 0, p3 = 0, r = 0;
      double v =  1 + 2. / (gXMax[j] - gXMin[j]) * (x[j] - gXMax[j]);
      // what is the power to use!
      switch(power) {
      case 1: r = 1; break; 
      case 2: r = v; break; 
      default: 
        p2 = v; 
        for (k = 3; k <= power; k++) { 
          p3 = p2 * v;
          p1 = p2; p2 = p3; 
        }
        r = p3;
      }
      // multiply this term by the poly in the jth var
      term *= r; 
    }
    // Add this term to the final result
    returnValue += term;
  }
  return returnValue;
}

// EOF for MDF_2022_GTMC_TEST_FINAL3.C
