// -*- mode: c++ -*-
// 
// File MDF_CARBON_MC_3_75_mwpc_5_withTx.C generated by TMultiDimFit::MakeRealCode
// on Sun Jul 24 12:30:45 2022
// ROOT version 6.26/02
//
// This file contains the function 
//
//    double  MDF(double *x); 
//
// For evaluating the parameterization obtained
// from TMultiDimFit and the point x
// 
// See TMultiDimFit class documentation for more information 
// 
//
// Static data variables
//
static int    gNVariables    = 10;
static int    gNCoefficients = 30;
static double gDMean         = 7.70504;
// Assignment to mean vector.
static double gXMean[] = {
  0.084903, 0.0732591, -0.000727632, 0.0120251, -0.0189016, -0.141768, 0.0134026, -0.00446799, -0.318811, -0.0317369 };

// Assignment to minimum vector.
static double gXMin[] = {
  -10.3666, -10.1672, -382.161, -0.0199998, -0.0199882, 4.88208, -28.4992, 495.201, 0.0550755, -0.0208033 };

// Assignment to maximum vector.
static double gXMax[] = {
  10.3622, 10.289, -212.164, 0.0199954, 0.0199971, 126.08, 29.2014, 735.196, 0.234377, 0.0227239 };

// Assignment to coefficients vector.
static double gCoefficient[] = {
  -2.00282,
  -3.46567,
  0.00318142,
  2.02552,
  0.757624,
  -0.959768,
  -1.41168,
  0.878811,
  -0.0114654,
  0.0894255,
  1.30494,
  -0.229824,
  -0.971314,
  -0.000274125,
  -0.00526423,
  0.422584,
  -0.509147,
  0.817464,
  0.0174657,
  -0.0129465,
  -0.0245888,
  -0.00267263,
  0.0137063,
  -0.0144563,
  -0.120599,
  0.0549254,
  0.120719,
  0.0562973,
  0.0154316,
  0.00891299
 };

// Assignment to error coefficients vector.
static double gCoefficientRMS[] = {
  2.19558e-11,
  7.12059e-11,
  4.12286e-11,
  1.84549e-10,
  5.51774e-11,
  9.27599e-11,
  3.00859e-10,
  2.42076e-10,
  5.4349e-11,
  5.18767e-11,
  3.77881e-10,
  1.3178e-10,
  4.07976e-10,
  1.0634e-10,
  1.03771e-10,
  2.77441e-10,
  4.09966e-10,
  5.53785e-10,
  6.75498e-11,
  1.09227e-10,
  1.60458e-10,
  4.60573e-11,
  4.6875e-11,
  6.77149e-11,
  3.54421e-10,
  2.44263e-10,
  3.40505e-10,
  2.47154e-10,
  1.80069e-10,
  2.2161e-10
 };

// Assignment to powers vector.
// The powers are stored row-wise, that is
//  p_ij = gPower[i * NVariables + j];
static int    gPower[] = {
  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  2,  1,
  2,  1,  1,  1,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  3,  1,
  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  2,  1,  1,  1,  1,  2,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  4,  1,
  1,  1,  1,  2,  1,  1,  1,  1,  3,  1,
  3,  1,  1,  1,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  3,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  5,  1,
  1,  1,  1,  3,  1,  1,  1,  1,  2,  1,
  1,  1,  1,  2,  1,  1,  1,  1,  4,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,
  1,  1,  1,  1,  1,  1,  1,  1,  1,  3,
  1,  1,  1,  3,  1,  1,  1,  1,  3,  1,
  1,  1,  1,  1,  1,  1,  1,  1,  6,  1,
  1,  1,  1,  2,  1,  1,  1,  1,  5,  1,
  1,  1,  1,  4,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  1,  1,  1,  2,  1,  1,  1,
  1,  3,  1,  1,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  1,  1,  2,  1,  1,  1,  2,
  1,  1,  1,  2,  1,  1,  1,  1,  1,  3,
  1,  1,  1,  1,  1,  1,  2,  1,  2,  2,
  1,  1,  1,  3,  1,  1,  1,  1,  4,  1,
  1,  1,  1,  4,  1,  1,  1,  1,  3,  1,
  2,  1,  1,  2,  1,  1,  3,  1,  3,  1,
  1,  2,  1,  1,  1,  1,  1,  1,  1,  2,
  1,  1,  1,  1,  1,  1,  2,  1,  2,  3,
  1,  2,  1,  1,  1,  1,  1,  1,  2,  3
};

// 
// The function   double MDF(double *x)
// 
double MDF(double *x) {
  double returnValue = gDMean;
  int    i = 0, j = 0, k = 0;
  for (i = 0; i < gNCoefficients ; i++) {
    // Evaluate the ith term in the expansion
    double term = gCoefficient[i];
    for (j = 0; j < gNVariables; j++) {
      // Evaluate the polynomial in the jth variable.
      int power = gPower[gNVariables * i + j]; 
      double p1 = 1, p2 = 0, p3 = 0, r = 0;
      double v =  1 + 2. / (gXMax[j] - gXMin[j]) * (x[j] - gXMax[j]);
      // what is the power to use!
      switch(power) {
      case 1: r = 1; break; 
      case 2: r = v; break; 
      default: 
        p2 = v; 
        for (k = 3; k <= power; k++) { 
          p3 = p2 * v;
          p1 = p2; p2 = p3; 
        }
        r = p3;
      }
      // multiply this term by the poly in the jth var
      term *= r; 
    }
    // Add this term to the final result
    returnValue += term;
  }
  return returnValue;
}

// EOF for MDF_CARBON_MC_3_75_mwpc_5_withTx.C
