// -*- mode: c++ -*-
// 
// File MDF_Tx_CARBON_MC_3_75_mwpc_5.C generated by TMultiDimFit::MakeRealCode
// on Thu Jul 21 13:59:21 2022
// ROOT version 6.26/02
//
// This file contains the function 
//
//    double  MDF(double *x); 
//
// For evaluating the parameterization obtained
// from TMultiDimFit and the point x
// 
// See TMultiDimFit class documentation for more information 
// 
//
// Static data variables
//
static int    gNVariablesTx    = 9;
static int    gNCoefficientsTx = 30;
static double gDMeanTx         = -0.000749333;
// Assignment to mean vector.
static double gXMeanTx[] = {
  0.076642, 0.0764327, -0.00777781, -0.0186869, -0.11273, -0.0117625, -0.00296344, -0.255475, 0.0590612 };

// Assignment to minimum vector.
static double gXMinTx[] = {
  -10.6058, -10.2472, -382.161, -0.0199998, 4.18165, -28.4992, 495.201, 0.0502297, -0.0394145 };

// Assignment to maximum vector.
static double gXMaxTx[] = {
  10.3622, 10.289, -211.261, 0.0199971, 126.08, 30.6741, 735.196, 0.238305, 0.0355781 };

// Assignment to coefficients vector.
static double gCoefficientTx[] = {
  -0.00879347,
  -0.0225357,
  0.1356,
  -0.00152663,
  0.00431662,
  -0.000198761,
  -0.000225988,
  -0.100452,
  -0.0384367,
  0.00167458,
  -0.0245441,
  0.00328011,
  -0.000517042,
  -0.000225802,
  2.31136e-05,
  0.00073048,
  -0.00754417,
  0.000881236,
  -0.000493645,
  -0.00049048,
  0.00115052,
  -0.00157043,
  0.00355122,
  -0.000732298,
  -0.0227586,
  -0.00791164,
  0.0274413,
  -0.0126264,
  -0.000547917,
  -0.000929778
 };

// Assignment to error coefficients vector.
static double gCoefficientRMSTx[] = {
  1.61447e-11,
  8.23884e-11,
  1.84414e-10,
  1.24934e-10,
  5.57773e-11,
  1.18502e-10,
  7.8713e-11,
  1.37642e-10,
  5.45275e-11,
  1.30625e-10,
  5.46338e-11,
  2.64275e-10,
  2.38556e-11,
  5.09288e-11,
  3.98267e-11,
  7.09198e-11,
  3.31585e-10,
  1.99185e-10,
  1.41165e-10,
  8.38792e-11,
  1.95308e-10,
  1.86555e-10,
  2.68561e-10,
  1.71053e-10,
  5.28758e-10,
  2.09615e-10,
  7.14909e-10,
  3.16645e-10,
  8.175e-11,
  8.97878e-11
 };

// Assignment to powers vector.
// The powers are stored row-wise, that is
//  p_ij = gPower[i * NVariables + j];
static int    gPowerTx[] = {
  1,  1,  1,  1,  1,  1,  1,  1,  1,
  2,  1,  1,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  1,  2,  1,  1,  1,  1,
  1,  1,  1,  1,  2,  1,  1,  2,  1,
  2,  1,  2,  1,  1,  1,  1,  1,  1,
  2,  1,  1,  1,  1,  1,  1,  3,  1,
  4,  1,  1,  1,  1,  1,  1,  1,  1,
  1,  1,  1,  1,  1,  1,  1,  2,  1,
  1,  1,  1,  1,  1,  1,  2,  1,  1,
  1,  1,  1,  1,  1,  1,  1,  3,  1,
  1,  1,  1,  1,  1,  1,  2,  2,  1,
  1,  1,  2,  1,  1,  1,  1,  3,  1,
  1,  1,  2,  1,  1,  1,  1,  1,  1,
  2,  1,  3,  1,  1,  1,  1,  1,  1,
  3,  1,  1,  1,  1,  1,  1,  1,  1,
  1,  1,  2,  1,  2,  1,  1,  1,  1,
  1,  1,  2,  1,  2,  1,  1,  2,  1,
  2,  1,  2,  1,  1,  1,  1,  2,  1,
  1,  1,  2,  1,  2,  1,  2,  1,  1,
  2,  1,  2,  1,  1,  1,  2,  1,  1,
  2,  1,  2,  1,  2,  1,  1,  1,  1,
  3,  1,  2,  1,  2,  1,  1,  1,  1,
  1,  1,  2,  1,  4,  1,  1,  1,  1,
  1,  1,  1,  1,  1,  1,  1,  5,  1,
  1,  1,  2,  1,  1,  1,  1,  4,  1,
  1,  1,  2,  1,  1,  1,  2,  3,  1,
  1,  1,  2,  1,  2,  1,  1,  3,  1,
  2,  1,  2,  1,  1,  1,  1,  3,  1,
  1,  1,  2,  1,  1,  1,  3,  2,  1,
  1,  1,  3,  1,  2,  1,  1,  2,  1
};

// 
// The function   double MDF(double *x)
// 
double MDF_TX(double *x) {
  double returnValue = gDMeanTx;
  int    i = 0, j = 0, k = 0;
  for (i = 0; i < gNCoefficientsTx ; i++) {
    // Evaluate the ith term in the expansion
    double term = gCoefficientTx[i];
    for (j = 0; j < gNVariablesTx; j++) {
      // Evaluate the polynomial in the jth variable.
      int power = gPowerTx[gNVariablesTx * i + j]; 
      double p1 = 1, p2 = 0, p3 = 0, r = 0;
      double v =  1 + 2. / (gXMaxTx[j] - gXMinTx[j]) * (x[j] - gXMaxTx[j]);
      // what is the power to use!
      switch(power) {
      case 1: r = 1; break; 
      case 2: r = v; break; 
      default: 
        p2 = v; 
        for (k = 3; k <= power; k++) { 
          p3 = p2 * v;
          p1 = p2; p2 = p3; 
        }
        r = p3;
      }
      // multiply this term by the poly in the jth var
      term *= r; 
    }
    // Add this term to the final result
    returnValue += term;
  }
  return returnValue;
}

// EOF for MDF_Tx_CARBON_MC_3_75_mwpc_5.C
