/* Generated by Together */
#include "FairPassiveDet.h"

#include "FairGeoBuilder.h"     // for FairGeoBuilder
#include "FairGeoInterface.h"   // for FairGeoInterface
#include "FairGeoLoader.h"      // for FairGeoLoader
#include "FairGeoMedia.h"       // for FairGeoMedia

#include <TGeoCompositeShape.h>   // for TGeoCompositeShape
#include <TGeoManager.h>          // for TGeoManager, gGeoManager
#include <TGeoMatrix.h>           // for TGeoRotation
#include <TGeoPcon.h>             // for TGeoPcon
#include <TGeoVolume.h>           // for TGeoVolume, etc

class FairGeoMedium;

FairPassiveDet::~FairPassiveDet() {}

FairPassiveDet::FairPassiveDet()
    : FairModule("FairPassiveDet", "")
{}

FairPassiveDet::FairPassiveDet(const char* name, const char* title)
    : FairModule(name, title)
{}

FairPassiveDet::FairPassiveDet(const FairPassiveDet& rhs)
    : FairModule(rhs)
{}

void FairPassiveDet::ConstructGeometry()
{
    TString fileName = GetGeometryFileName();
    if (fileName.EndsWith(".geo"))
        ConstructASCIIGeometry();
    else if (fileName.EndsWith(".root"))
        ConstructRootGeometry();
    else
        std::cout << "Geometry format not supported " << std::endl;
}

FairModule* FairPassiveDet::CloneModule() const
{
    return new FairPassiveDet(*this);
}
