/********************************************************************************
 *    Copyright (C) 2014 GSI Helmholtzzentrum fuer Schwerionenforschung GmbH    *
 *                                                                              *
 *              This software is distributed under the terms of the             *
 *              GNU Lesser General Public Licence (LGPL) version 3,             *
 *                  copied verbatim in the file "LICENSE"                       *
 ********************************************************************************/
/* Generated by Together */
#include "FairPipe.h"

#include "FairGeoBuilder.h"     // for FairGeoBuilder
#include "FairGeoInterface.h"   // for FairGeoInterface
#include "FairGeoLoader.h"      // for FairGeoLoader
#include "FairGeoMedia.h"       // for FairGeoMedia

#include <TGeoCompositeShape.h>   // for TGeoCompositeShape
#include <TGeoManager.h>          // for TGeoManager, gGeoManager
#include <TGeoMatrix.h>           // for TGeoRotation
#include <TGeoPcon.h>             // for TGeoPcon
#include <TGeoVolume.h>           // for TGeoVolume, etc

class FairGeoMedium;

FairPipe::~FairPipe() {}

FairPipe::FairPipe()
    : FairModule("FairPipe", "")
{}

FairPipe::FairPipe(const char* name, const char* title)
    : FairModule(name, title)
{}

FairPipe::FairPipe(const FairPipe& rhs)
    : FairModule(rhs)
{}

void FairPipe::ConstructGeometry()
{
    TString fileName=GetGeometryFileName();
    if (fileName.EndsWith(".geo"))
        ConstructASCIIGeometry();
    else if(fileName.EndsWith(".root"))
        ConstructRootGeometry();
    else
        std::cout<< "Geometry format not supported " <<std::endl;
}

FairModule* FairPipe::CloneModule() const { return new FairPipe(*this); }
